POST  http://localhost:3003/team
Content-Type: application/json

{
    "name":"Ailton",
    "module": "0"
}

###

GET http://localhost:3003/team

###

PUT http://localhost:3003/team/update/006
Content-Type:  application/json

{
    "module": "1"
}